"""Simple rules against AgentSeism v1. No API, no runs.

    .venv/bin/python analysis/ci_v1/baseline_challenge.py > out.md

Four decision rules, each seeing the same per-task success counts:

  R1  naive aggregate:  mean(cand) - mean(base) <= -0.10
  R2  simple per-task:  some task with baseline >= 0.8 and drop >= 0.5
  R3  count heuristic:  some task with baseline >= 7/8 and candidate <= 2/8
                        (as fractions: >= 0.875 and <= 0.25)
  v1  AgentSeism:       gate 1 (population bootstrap) OR gate 2 (Fisher +
                        Bonferroni), through the product's own code paths

The engine is the one from operating_characteristics.py: gate 1 is verified
against the product's `_paired_bootstrap`, and gate 2 is `capability.evaluate`.
Every comparison is made in exact integer arithmetic, so a rule's threshold is
never missed by a float.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import operating_characteristics as oc  # noqa: E402
from agentseism import capability as cap  # noqa: E402
from agentseism.capability import TaskCounts as T  # noqa: E402

SIMS = 4000
RNG = np.random.default_rng(20260926)


def rules(b: np.ndarray, c: np.ndarray, n: int) -> dict[str, np.ndarray]:
    """b, c: (S, K) successes out of n. Returns one boolean array per rule."""
    s, k = b.shape
    d = c - b
    r1 = 10 * d.sum(axis=1) <= -n * k
    r2 = ((10 * b >= 8 * n) & (2 * (b - c) >= n)).any(axis=1)
    r3 = ((8 * b >= 7 * n) & (4 * c <= n)).any(axis=1)
    g1 = oc.g1_fires(d.astype(np.int32), n)
    g2 = np.array([bool(cap.evaluate(oc.spec(n), {f"t{j}": T(int(b[i, j]), n,
                                                              int(c[i, j]), n)
                                                  for j in range(k)})["fired"])
                   for i in range(s)])
    return {"R1": r1, "R2": r2, "R3": r3, "v1": g1 | g2,
            "v1 gate 1": g1, "v1 gate 2": g2}


def draw(pb, pc, n, sims=SIMS):
    k = len(pb)
    return (RNG.binomial(n, pb, size=(sims, k)),
            RNG.binomial(n, pc, size=(sims, k)))


COLS = ("R1", "R2", "R3", "v1", "v1 gate 1", "v1 gate 2")


def row(label, k, n, res):
    return (f"| {label} | {k} | {n} | "
            + " | ".join(f"{res[c].mean():.3f}" for c in COLS) + " |")


def main() -> None:
    p = print
    p("<!-- generated by analysis/ci_v1/baseline_challenge.py -->")

    # ── Stage A / B replay, as observed (n = 5) ──
    p("### C1. Replay of Stage A and Stage B (observed counts, n = 5)\n")
    p("Frozen v1 requires 8 trials for gate 2, so on 5-trial data it monitors "
      "nothing. The column `v1 @ n=5` applies the frozen rule mechanically at "
      "n = 5 (eligibility 0.875, which means 5/5), as in the OC study.\n")
    names = ["astropy", "django", "matplotlib", "seaborn", "flask"]
    stages = {"Stage A": ([5, 5, 5, 3, 5], [5, 5, 5, 2, 5]),
              "Stage B": ([5, 5, 5, 3, 5], [5, 0, 3, 0, 5])}
    p("| | R1 | R2 | R3 | v1 @ n=5 | why |")
    p("|---|---|---|---|---|---|")
    for st, (b, c) in stages.items():
        res = rules(np.array([b]), np.array([c]), 5)
        why = []
        agg = (sum(c) - sum(b)) / 25
        why.append(f"aggregate {agg:+.2f}")
        for nm, bb, cc in zip(names, b, c):
            if bb != cc:
                why.append(f"{nm} {bb}/5→{cc}/5")
        verdict = lambda x: "**REGRESSION**" if x[0] else "PASS"  # noqa: E731
        p(f"| {st} | {verdict(res['R1'])} | {verdict(res['R2'])} | "
          f"{verdict(res['R3'])} | {verdict(res['v1'])} | {'; '.join(why)} |")

    # ── false blocks on unchanged candidates ──
    p(f"\n### C2. False blocks on an unchanged candidate ({SIMS} draws per cell)\n")
    p("| null profile | K | n | " + " | ".join(COLS) + " |")
    p("|---|---|---|" + "---|" * len(COLS))
    nulls = {
        "all 0.95": lambda k: np.full(k, 0.95),
        "Stage-A-like (one 0.6, rest 0.95)": lambda k: np.r_[0.6, np.full(k - 1, 0.95)],
        "flaky agent, all 0.70": lambda k: np.full(k, 0.70),
        "spread 0.3–0.95": lambda k: np.linspace(0.3, 0.95, k),
    }
    for name, f in nulls.items():
        for k in (5, 7, 10):
            for n in (5, 8):
                r = f(k)
                p(row(name, k, n, rules(*draw(r, r, n), n)))

    # ── sensitivity ──
    p(f"\n### C3. Detection against real regressions, baseline 0.95 everywhere "
      f"({SIMS} draws per cell)\n")
    p("| regression | K | n | " + " | ".join(COLS) + " |")
    p("|---|---|---|" + "---|" * len(COLS))
    alts = {
        "broad −0.10": lambda k: np.full(k, 0.85),
        "broad −0.20": lambda k: np.full(k, 0.75),
        "broad −0.30": lambda k: np.full(k, 0.65),
        "one task → 0.50": lambda k: np.r_[0.50, np.full(k - 1, 0.95)],
        "one task → 0.25": lambda k: np.r_[0.25, np.full(k - 1, 0.95)],
        "one task → 0.10": lambda k: np.r_[0.10, np.full(k - 1, 0.95)],
        "Stage-B-like (0, 0.6, rest same)": lambda k: np.r_[0.0, 0.6, np.full(k - 2, 0.95)],
    }
    for name, f in alts.items():
        for k in (7,):
            for n in (5, 8):
                p(row(name, k, n, rules(*draw(np.full(k, 0.95), f(k), n), n)))

    # ── where R3 and gate 2 disagree, exactly ──
    p("\n### C4. Where R3 and v1 gate 2 decide differently on one task (n = 8)\n")
    p("Exact, by enumerating (baseline, candidate). "
      "`R3 only` means the heuristic blocks and gate 2 does not.\n")
    p("| K | R3 only | gate 2 only |")
    p("|---|---|---|")
    for k in range(1, 11):
        r3_only, g2_only = [], []
        for b in range(9):
            for c in range(9):
                r3 = 8 * b >= 7 * 8 and 4 * c <= 8
                g2 = oc.fires(b, c, 8, k)
                if r3 and not g2:
                    r3_only.append(f"{b}/8→{c}/8")
                if g2 and not r3:
                    g2_only.append(f"{b}/8→{c}/8")
        p(f"| {k} | {', '.join(r3_only) or '—'} | {', '.join(g2_only) or '—'} |")

    # ── the K choice: eligible tasks (frozen) vs the declared suite ──
    p("\n### C5. Gate 2 with K = eligible tasks (frozen) vs K = suite size "
      f"(n = 8, 20000 draws per cell)\n")
    p("The frozen spec divides α by the number of *eligible* tasks. When the "
      "agent is flaky few tasks are eligible, α/K relaxes, and the gate loosens "
      "exactly where noise is highest.\n")
    p("| scenario | K suite | mean eligible | gate 2, K = eligible | "
      "gate 2, K = suite | R3 |")
    p("|---|---|---|---|---|---|")
    rng = np.random.default_rng(7)
    scen = {
        "null, all 0.70": lambda k: (np.full(k, .7), np.full(k, .7)),
        "null, spread 0.3–0.95": lambda k: (np.linspace(.3, .95, k),) * 2,
        "null, Stage-A-like": lambda k: (np.r_[.6, np.full(k - 1, .95)],) * 2,
        "one task 0.95 → 0.25": lambda k: (np.full(k, .95),
                                           np.r_[.25, np.full(k - 1, .95)]),
        "one task 0.95 → 0.10": lambda k: (np.full(k, .95),
                                           np.r_[.10, np.full(k - 1, .95)]),
    }
    for name, f in scen.items():
        for k in (5, 7, 10):
            pb, pc = f(k)
            b = rng.binomial(8, pb, size=(20000, k))
            c = rng.binomial(8, pc, size=(20000, k))
            elig = (b >= 7).sum(axis=1)
            by_elig = np.array([any(oc.fires(int(b[i, j]), int(c[i, j]), 8,
                                             max(1, int(elig[i])))
                                    for j in range(k)) for i in range(len(b))])
            by_suite = np.array([any(oc.fires(int(b[i, j]), int(c[i, j]), 8, k)
                                     for j in range(k)) for i in range(len(b))])
            r3 = ((b >= 7) & (c <= 2)).any(axis=1)
            p(f"| {name} | {k} | {elig.mean():.1f} | {by_elig.mean():.4f} | "
              f"{by_suite.mean():.4f} | {r3.mean():.4f} |")

    # ── scaling with suite size, exact ──
    p("\n### C6. Family-wise false block as the suite grows (n = 8, exact)\n")
    p("Every task at the same true rate p in both arms. Power is for one task "
      "0.95 → 0.10. Gate 2 uses K = suite size.\n")
    p("| p | K | R3 false block | gate 2 false block | R3 power | gate 2 power |")
    p("|---|---|---|---|---|---|")
    from math import comb

    def bn(x, q):
        return comb(8, x) * q ** x * (1 - q) ** (8 - x)
    r3_power = sum(bn(b, .95) * bn(c, .10) for b in (7, 8) for c in (0, 1, 2))
    for q in (0.7, 0.9):
        r3_q = sum(bn(b, q) * bn(c, q) for b in (7, 8) for c in (0, 1, 2))
        for k in (5, 10, 20, 50):
            g2_q = sum(bn(b, q) * bn(c, q) for b in range(9) for c in range(9)
                       if oc.fires(b, c, 8, k))
            p(f"| {q} | {k} | {1 - (1 - r3_q) ** k:.4f} | "
              f"{1 - (1 - g2_q) ** k:.4f} | {r3_power:.3f} | "
              f"{oc.g2_prob(.95, .10, 8, k):.3f} |")


if __name__ == "__main__":
    main()
