"""Data for the Regression Explorer, generated by the real decision engine.

    python docs/figures/make_explorer_data.py [out.js]

Runs the three `seism demo` scenarios through the product (the same
`run_scenario` the demo uses) and writes `window.EXPLORER_DATA = {...}`:

- every run's outcome (the stated fixture);
- per-task counts;
- the broad gate's effect, interval and bootstrap distribution;
- the capability gate's per-task p-values, limit and decisions;
- the verdict.

The bootstrap distribution is rebuilt with the product's own algorithm (seed
0, 2000 resamples of tasks), and the script asserts that its percentiles equal
the interval the product reported, so the chart cannot drift from the
decision.
"""

from __future__ import annotations

import json
import random
import statistics as st
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1] / "src"))

from agentseism import demo  # noqa: E402

N_BOOT, SEED = 2000, 0          # as in agentseism.cli._paired_bootstrap
KEYS = ["noise", "collapse", "insufficient"]


def bootstrap_means(base: dict[str, str], cand: dict[str, str]) -> tuple[list[float], list[str], list[float]]:
    """The product's paired bootstrap over tasks, returning every resample mean."""
    tasks = sorted(base)                      # _measure keys sort the same way
    diffs = [cand[t].count("1") / len(cand[t]) - base[t].count("1") / len(base[t])
             for t in tasks]
    rng = random.Random(SEED)
    means = [st.mean([diffs[rng.randrange(len(diffs))] for _ in diffs])
             for _ in range(N_BOOT)]
    return means, tasks, diffs


def scenario(i: int, s: demo.Scenario, r: dict) -> dict:
    d, cap, v = r["detail"], r["capability"], r["verdict"]
    means, order, diffs = bootstrap_means(s.baseline, s.candidate)
    ms = sorted(means)
    lo, hi = ms[int(.025 * N_BOOT)], ms[int(.975 * N_BOOT) - 1]
    assert (round(lo, 12), round(hi, 12)) == (round(d["ci"][0], 12), round(d["ci"][1], 12)), \
        "explorer bootstrap does not reproduce the product's interval"
    f = r["contract"].features["task_success"]
    capdetail = {Path(t).stem: dd for t, dd in cap["detail"].items()}
    tasks = []
    for t in s.baseline:                       # the fixture's display order
        dd = capdetail[t]
        tasks.append({
            "name": t, "baseline": s.baseline[t], "candidate": s.candidate[t],
            "gate": dd.get("decision", "NOT MONITORED"),
            "p": dd.get("p"), "drop": dd.get("drop"),
            "why_not_monitored": dd.get("not_monitored"),
        })
    return {
        "key": KEYS[i - 1], "title": s.title, "story": s.story, "trials": s.trials,
        "tasks": tasks,
        "score": {"baseline": d["baseline"], "candidate": d["candidate"]},
        "broad": {"status": r["broad"], "effect": d["effect"], "ci": d["ci"],
                  "threshold": float(f["practical_threshold"]),
                  "per_task": dict(zip([o for o in order], diffs)),
                  "boot_means": [round(m, 6) for m in means]},
        "capability": {"k": cap["k"], "limit": cap["alpha_per_task"],
                       "eligible": [Path(t).stem for t in cap["eligible"]],
                       "fired": [Path(t).stem for t in cap["fired"]],
                       "warnings": [Path(t).stem for t in cap["warnings"]],
                       "min_trials": int(f["capability_regression"]["minimum_evidence"]
                                         ["trials_per_condition"]),
                       "eligibility": f["capability_regression"]["eligibility"]["baseline_success_min"],
                       "drop_threshold": f["capability_regression"]["practical_threshold"]},
        "verdict": v["verdict"],
    }


def build() -> str:
    with tempfile.TemporaryDirectory() as t:
        rs = [demo.run_scenario(i, s, Path(t)) for i, s in enumerate(demo.SCENARIOS, 1)]
    data = {"source": "seism demo scenarios, decided by AgentSeism's engine",
            "scenarios": [scenario(i, s, r) for i, (s, r)
                          in enumerate(zip(demo.SCENARIOS, rs), 1)]}
    return ("// generated by agentseism docs/figures/make_explorer_data.py; do not edit\n"
            "window.EXPLORER_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")


if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "explorer-data.js"
    out.write_text(build())
    print("wrote", out)
